@extends('layouts.plantillaCuerpo')
@section('title','Productos')
@section('header')
    @include('_components.header')
@endsection
@section('categorias')
    @include('_components.categorias')
@endsection
@section('footer')
    @include('_components.footer')
@endsection
