@extends('layouts.plantillaPagoRealizado')
@section('title','Productos')
@section('header')
    @include('_components.header')
@endsection
@section('tick')
    @include('_components.pagoRealizado')
@endsection
@section('footer')
    @include('_components.footer')
@endsection
